spring.application.name=demo
spring.datasource.url=jdbc:postgresql://localhost:5432/vente_chaussures
spring.datasource.username=postgres
spring.datasource.password=bc
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
